### ISSUE TITLE
add component module

### ISSUE THREAD

**Issue by mpenet** [mpenet/alia#51]
Simple alia components for session/cluster.

**Comment by d-t-w** [comment]
We use alia+component at SMX, not only for lifecycle and DI of the session/cluster, but we also optionally configure the connection component with cql / hayt statements which are converted into PreparedStatements at component system startup and accessible via the connection.

**Comment by mpenet** [comment]
We do something similar as well. But I am just unsure on how to split this for a module here. 

There are a few possibilities: 

* 3 components (cluster, session, statement**s**)

* just one that covers all of these via options.

* one with session+cluster another for statements

In our apps we have a cassandra component that holds cluster+session and then the prepared statements are parts of the cassandra implementations of "stores" which depends on that component. But there is an argument in favor of splitting cluster/session, as you could have multiple session per cluster instances (if you deal with multiple keyspaces for instance). 

The 3 part split is the more modular, it does require more ceremony for setup tho, but then you can build any other design on top.

How do you see that?

**Comment by d-t-w** [comment]
@coltnz is happy to share SMX's alia/component integration, it's available for you to peruse here:

https://github.com/SMX-LTD/cassandra-component/blob/master/src/smx/cassandra/component.clj

It's probably not immediately perfect for a library, but you can see the approach we take. There's also some schema dotted around that might be useful, though I never did quite get to enumerating all the fields in the Cluster config.

Of the options you list, I guess your preference will be influenced by how you slice up your applications. We tend to create web-services that are a component system, and each route/handler of that web-service is a component within that system. Handlers perform different actions but often have a common interaction with C*, creating an event or reading/writing domain data.

We have a single component called Connection which is effectively a session++. It is created with a keyspace (required) and queries (optional). It has a Cluster dependency. By this method we can have multiple connections in a system, and each connection creates PreparedStatements applicable to that keyspace from its configured queries at start. Our handlers (or other components) have a connection as a dependency, they could chose to create their own prepared statements on start with the connection they have as a dependency, but we tend not to do that.

Some notes:

Layout: we loosely follow prismatics ns organization style: https://github.com/plumatic/eng-practices/blob/master/clojure/20130927-ns-organization.md

Configuration: we parse EDN into a format suitable for creating a cluster. It's not complete, but a start.

Cluster only requires lifecycle behaviour not DI, so rather than wrap with a defrecord I:

```clojure
(extend-protocol cp/Lifecycle
  Cluster
  (start [this]
    (log/info "initializing cluster")
    (.init this))
  (stop [this]
    (log/info "stopping cluster")
    (.close this)
    (log/info "cluster stopped")
    this))
```

Schema. I delineate between a RawQuery (strings or hayt), AliaExecutable (things that I can alia/execute), Executable (things I can execute with the method defined lower in the ns), Vals (things that can be passed to a PreparedStatement), Command (things that I can convert into a BoundStatement).

You might not find any of the Schema particularly useful, it's possibly a bit specific to my needs, and a remnant of my extending Alia a little bit an understanding the boundaries of the functions I was working with.

Connection. Responsible for starting/stopping a session and initializing PreparedStatements for a keyspace. Is the key to all C* interaction via execute and execute-batch.

execute, execute-batch. We only use execute-chan-buffered due to https://github.com/mpenet/alia/issues/29 (we have one approach to handling exceptions with core.async and that revolves around ensuring the exception is placed on the channel, not potentially thrown when iterating over the ResultSet provided by execute-chan)

Usage.

Say I have a ns which defines functions for reading and writing events.

It can define some queries:

```clojure
(def read-queries
  "Queries for reading events from the catalog or time-series"
  {::read-catalog     "SELECT * ..."
   ::read-time-series "SELECT * ..."})

(def write-queries
  "Queries for writing events to the catalog or time-series"
  {::write-catalog     "INSERT...)"
   ::write-time-series "INSERT..."})

(def queries (merge read-queries write-queries))
```

and some functions that use a connection which is expected to have those queries available

```clojure
(s/defn read-catalog :- (es.async/chan Event)
  "Find events in the catalog by id"
  ([connection id]
   (read-catalog connection id nil))
  ([connection :- Connection
    id :- Id
    opts]
   (cassandra/execute connection ::read-catalog (assoc opts :values id)))))
```

the connection is configured to have those queries (and maybe others)

```clojure
(-> (cp/system-map
          ;; cluster and connection
          :cluster (cassandra/->cluster (:cluster config))
          :connection (cassandra/->connection
                        "sandbox"
                        (merge
                          cassandra.event/queries
                          cassandra.rcn/queries))
...
```

if I want to be defensive, on startup any component can confirm that the connection it has configured contains the prepared statements it expects to use

```clojure
cp/Lifecycle
  (start [this]
    (cassandra/has-prepared? connection event/queries)
...
```

**Comment by mpenet** [comment]
Thanks for sharing that, this is a really interesting approach. 
It is somewhat similar to what I had in mind but goes further, I might go with something more minimalist tho. But I am not rushing to do this, I will try to think about it a bit more. 
One thing I probably wont provide is an alia api facade that use the components directly, it's reasonable to do this at the app level, but I am not sure it's something desirable at alia's level. But I like the Session/Cluster/Statements/Connection split, it feels right.

**Comment by mpenet** [comment]
Well the alia api layer you provide is so thin I might be ok with including something similar after all, it's optional anyway and it's saves some typing.

**Comment by d-t-w** [comment]
Could be slightly tricky providing facade for each of execute, execute-chan, execute-chan-buffered, and execute-manifold, only because they are all in separate modules, so the dependency graph between component module <-> alia, alia-async, alia-manifold might be complicated.

**Comment by d-t-w** [comment]
That said I see a real value in it myself, but I only use execute-chan-buffered and I don't need to worry about how the modules of a library hang together.

**Comment by mpenet** [comment]
It's not so tricky, it's possible to use macro magic to do conditional compilation depending on the presence of this or that module (same as https://github.com/mpenet/hayt/blob/master/src/clj/qbits/hayt.clj#L16-L21). But I am not rushing into this just yet.

**Comment by d-t-w** [comment]
Hey Max, 

I cleaned up the smx/component repository slightly and wrote a blog post about how I use component which sheds a little light on why my code is structured the way it is (mostly the lack of a Connection protocol). FYI http://derek.troywest.com/articles/how-i-use-component

**Comment by mpenet** [comment]
Hey Derek, 

Very interesting post, thanks for the pointer! It reminded me I need to look into this further as soon as I have some free time. 

cheers!

**Comment by d-t-w** [comment]
Both a WIP, but I've created a couple of projects that manage C*/Alia state via:

Component - https://github.com/troy-west/archi
Integrant - https://github.com/troy-west/archo

They're fairly opinionated, following the style I have in place across my client projects for managing prepared statements, UDT encoders, clusters, sessions, etc. I'm going to write a little about my preference for Integrant and add to those repos over the holiday period.

**Comment by mpenet** [comment]
Cool stuff Derek. I have yet to look into Integrant. 

I am thinking I will probably add a section on the readme that references libraries/tools using alia after the holidays, these are useful and also good examples. Alternatively if you're up for it, feel free to send a PR for that, but as almost everybody I am sure you'll be too busy stuffing yourself with turkey & other goodies these next few days :)

**Comment by d-t-w** [comment]
Thanks max, I'm going to roll those into a single library, maybe modules for component / integrant / x, hopefully get around to it this weekend. Will raise a PR once it's done and released.

**Comment by pyr** [comment]
FWIW, here's what I've started working with for the upcoming pithos release:

https://gist.github.com/aab3821f780d32ff761893000b21aef2

Having this allows me to share clusters and retrieve named sessions from them.
Here's a sample use:

```clojure
(def queries
  "Cassandra queries"
  {::by-name   {:statement (select :bucket (where [[= :name ?]]) (limit 1))
                :opts      {:consistency   :quorum
                            :result-set-fn vector-result
                            :row-generator row->bucket}}
   ::by-tenant {:statement (select :bucket (where [[= :tenant ?]]))
                :opts      {:consistency :quorum
                            :result-set-fn vector-result
                            :row-generator row->bucket}}
   ::set-cors  {:statement (h/update :bucket (set-columns [[:cors ?]])
                                     (where [[= :name ?]]))}
   ::set-acl   {:statement (h/update :bucket (set-columns [[:acl ?]])
                                     (where [[= :name ?]]))}
   ::create    {:statement (insert :bucket
                                   (values [[:name ?] [:tenant ?] [:created ?]
                                            [:region ?] [:acl ?] [:cors ?]]))}
   ::delete    {:statement (delete :bucket (where [[= :name ?]]))}})

(defrecord CassandraBucketStore [keyspace cluster query! cassandra]
  component/Lifecycle
  (start [this]
    (assoc this :query! (query-functions cassandra cluster keyspace queries)))
  (stop [this]
    (query! ::pithos.cassandra/stop)
    (assoc this :query! nil)))
```

This lets you do `(query! ::by-name name)` from the component.
