### ISSUE TITLE
Tombstone on null insertion (prepared statements)

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#66]
Hi Max,

 Currently it's possible that the insertion of a nil value via a prepared statement may cause an un-purgeable tombstone (the only way to avoid it pre C* 2.2 is to use a prepared-statement without that parameter set when the value is nil)

 I can see these created in my own case but haven't hit the threshold where it can become problematic (droppable-tombstone-ratio defaults to 0.2).

see: http://thelastpickle.com/blog/2016/09/15/Null-bindings-on-prepared-statements-and-undesired-tombstone-creation.html 

 So, post C* 2.2+ with driver 3.0.0+ you can chose to leave parameters in a prepared statement unset, and no tombstone is created (previous versions you must explicitly setToNull). 

 We could leave values unset where we're binding named parameters, I'd be happy to go ahead and scratch up an implementation but I'm wondering what the best way to go about it may be. 

 Currently we have a PNamedBinding protocol in  the codec ns with:

```clojure
 nil
  (-set-named-parameter! [_ settable name]
    (.setToNull ^SettableByNameData settable name))
```
 
 Would it be sensible to provide a mechanism to re-extend nil to this protocol specifically for 2.2+ where the behaviour is basically a no-op. Let me know your thoughts.

**Comment by mpenet** [comment]
Hi Derek, 

Nice find (again). I am on a trip until Monday tho, but I ll try to have a deeper look into this. My gut feeling just after reading the issue, is that we might take the no-op solution (but I want to make sure this has no side effect). I need to experiment a bit with this on my side first.

**Comment by mpenet** [comment]
I don't think we can do what you suggest. 

The problem is that sometimes you'd not want to set a field to null, but sometimes you'd want to (ex: deletion of a column). It really depends on the query/use case, not setting a col value to null will not "delete" it from what I understand.  Sadly, the only workaround for 2.2 seems  to be what the post suggest (creating variations of the prepared statements you need with cols not set).

This raises another issue tho, with positional parameters we always bind nil columns, and the user cannot bind by index and leave values unset, like in the post you mention. I think we need to provide another arity for alia/bind that allows this. 

Ultimately the user has to know these shortcomings of cassandra for now. I don't think there is a way to abstract this away right now. 

There could be something, but I am not sure I'd like it, this could however be something optional with low impact on the rest anyway: we could add a datatype that basically means "Unset" and extend the protocols to no-op for this type. This would require us to change a bit the positional bind function to use the indexed based .bind method tho. 

Thoughts?

**Comment by d-t-w** [comment]
Right, I understand your point re: wanting to delete a column, and I can imagine that's a fairly normal use-case. That is tricky.

In my case I have a table that may have 10+ fields, any of which can be nil, and to produce PreparedStatements for each possibility becomes combinatorial, though I would do that if this was a pressing concern.

You're right that a global set/unset approach isn't the way to go. I will take a look at the current impl because I can't quite remember how maps are converted to named bindings, but perhaps we could use a rule similar to:

1. Where a key exists in the map of parameters, the value is applied
2. Where a key does not exist the value is left unset

e.g. Where a PS has a single named parameter, binding:

`{:parameter nil}` : sets the parameter to nil
`{}` : leaves the parameter unset

However I'm not entirely sure how Alia could determine which keys are missing from any map of named parameters, it may be possible to get a set of params from the PS itself, perhaps memoized.

**Comment by mpenet** [comment]
I think the current state is not bad (it what you describe):
We only bind null when you explicitly pass nil values, if you omit the map-entry it's a no op. There was a pr to set all to nil when unspecified but we didnt merge it ultimately.

**Comment by mpenet** [comment]
Ahh! Didnt see your edit ;)

It still bad for 2.2 but I am not sure we can do much. We could provide some high level clutch function that does the multiple prepared statement but I am not sure I d put it in core since 2.2 is close to EOL.

**Comment by d-t-w** [comment]
Great thanks Max, as-is seems good for now.
