### ISSUE TITLE
Adv. codecs extensions (ex: udt instances as records)

### ISSUE THREAD

**Issue by ifesdjeen** [mpenet/alia#67]
Hi Max, 

It's more as an "open discussion" thing rather then the issue. If you prefer to have such things in email, please let me know.

Thing is that it's quite easy to convert record to UDT. Although as discussed [here](https://github.com/pyr/cyanite/pull/248) converting it back is a bit trickier (although possible). 

What I wanted to suggest / had in mind is to have pluggable backends that one could register during connection (or similar) and that depend on the `type` field of UDT itself, that would allow converting certain UDT types back to records/deftypes without using row generators (also because as it seems, row generators are already one level further: UDT is already converted to map). 

So idea is: 
- (1) UDT in -> custom object (record, deftype instance, etc) out
- Register once
- Automatic inference based on UDT type, calling the (1)

What do you think about this idea?

**Comment by mpenet** [comment]
Hi Alex,

That's a good idea, and something I have given some thoughts about already.
As mentioned this is a separate thing from RowGenerators, both make sense on their own.

I actually have a few notes about dealing with UDT fields <-> record
instances converters. There are a few options as to how/where to
implement this.

A few of my requirements would be:

* The UDT codec registry it has to be cluster+keyspace
  local. That doesn't necessarily mean "stored" on Cluster java
  instance, but it was to be bound to one. The user should be able to
  have different UDT codec on different Cluster + keyspaces. I
  guess this is similar to what you mean with "register once". Same
  scoping rules as udt have themselves actually.

* I want the UDT codec to behave like the main decoding protocol. The
  UDT codec must respect whatever the main decoding protocol
  implement/satisfies, ex if an UDT value contains a Date type and the
  user has extended it to have joda instances returned, it should
  abide to this.

* This should handle recursive definitions: a UDT value is now decoded
  in a recusive manner: ex. it can have a value that's a collections
  of UDT values and still respect the main decoding protocol.

On the implementations side there could be a few ways to achieve this:

One could maybe uses the custom Codec feature of the java-driver, but
I am not sure this would allow to respect the main decoding protocol
extension easily. I was planning to play with this and see how it
could be done but my gut feeling is not so good about it.

Alternatively we could just have a globally available mutable registry that knows
per [cluster, keyspace, udt-name] how to decode an udt value and leave it
at that.

I have the feeling that the latter is the way to go.

This could be a simple atom/volatile map based registry in
qbits.alia/codec and a simple deref get call to grab a potential
decoder from qbits.alia.codec/decode-row (assuming we can get back to
cluster instance + keyspace name without too much shuffling from
there).

If we want to make it really easy to implement we can have the
"registry" be an option passed to execute functions, no need to mess
around with a global mutable ref and walk back to cluster/keyspace
meta data from a result-set this way, this might be the most performant way (no perf penality for people who don't care about custom udt decoding and small "registry"), but in a pure API design point of view "one time" binding of this stuff at a higher level might be nicer.


Thoughts?

**Comment by mpenet** [comment]
So I thought about this a bit more this afternoon:

I think we can simplify the design a bit by saying a single Session is
bound to a single "registry" instance (no matter the keyspace). If a
user has 2 udts with the same name in different keyspaces we can solve
the problem differently or "suggest" he uses 2 different
Sessions.

Imho we can also expand a bit the scope of this by saying this not
only can apply to udts, but to any other type. What we might want is
custom codec (decoder/encoder) instances per Session (and/or query).

In the code this would translate by changing the current
encoder/decoder impl to be applied to a reified instance of the Codec
protocol by default, and allow the user to create his own reified
instances of it to set/use at Session but also possibly Query level. A
Codec instance can then have whatever special rules to encode/decode
an UDT (via some kind of registry), but also any other type in
isolation to other potential existing Codec impls. Then it's a matter
of making a nice API for the creation of these, as we might not want
to expose to users all the gory details.

If someone wants to use the same Session instance to interact with
many keyspaces and use different custom registries (the limitation I
mentioned earlier), he could just overwrite the Codec instance at query
level too.

When execute will be called it will follow the following rule:

if a custom Codec impl was passed to execute, use this one.
otherwise if a custom Codec impl was set at session level use this one
otherwise default to a default instance that lives in qbit.alia.codec.

This is somewhat similar to what the driver provides with slightly
different semantics but just as powerful imho.

There should also be nearly no perf penalty from having this
flexibility.

I will probably give a try at implementing this on Monday morning, this should be quite simple to add and we should have something to test that day.

**Comment by ifesdjeen** [comment]
I like the idea. I, too, think that implementing it recursively might be a bit tricky. On the other hand, there's a possibility to hook in / wrap `get<X>`. I also agree the option 2 sounds more realistic to work. Same with `Codec` for any time - I completely agree that there might be benefit from allowing converting any type to the data structure of your preference.

As regards registry vs passing to `execute` functions, I'd personally favour the former, as it's a bit easier for the application developer to define it all in one place. 

Thanks so much for taking a look into it!

**Comment by mpenet** [comment]
Oh It will work recursively :), it already does at every level (collection types, tuples, udts, (named or positional) prepared statement values, batches etc) in master. 

I saw you mention wrap/get I guess that's ByteBuffer related, but I am not sure I want to go that low level; the driver already does already all the heavy lifting for us here and this also has the advantage to not require to have to mess with protocol versions, this way we support basically any cassandra version the driver does out of the box. That said, if we want to go this way it only requires to move 1 fn, but this makes writing user codecs a bit more of a pita imho.

So I am playing a bit with this idea in a branch.
We have 2 protocols that are basically controlling how to translate a java type coming from or going to cassandra into a "codec" function call per type (also protocol backed), and from there we allow users to supply their own codec instances (right now at execute level, but I ll add session level later today or tomorrow). Ultimately the API is very similar from master, and adding custom record encoder/codec is super easy. 

I only wish we could also have first class Encoding/Decoding table, but that's a bit messy if we want to retain the performance we have right now. So there's only one, but since it only dispatches to a user supplied codec instance, this give enough freedom to the end-user.

I hacked a udt registry on top of this and this seems to work fine, and it's contained in a codec instance too, which is what we wanted.

The good news is that performance is identical to master in my (un-scientific) benchmarks.
This is all playground still, I need to add real tests and see if I can avoid breaking backward compat,given that includes a lot of changes internally, and also make the udt stuff less hackish than it is at the moment (should be easy).
